### PR TITLE
Add (partial) support for Virtual Events extension

### PR DESCRIPTION
**Pull request by justlevine**
This PR adds partial support for [Virtual Events extension](https://theeventscalendar.com/products/wordpress-virtual-events/).

## What it includes: 
The meta fields from `src/Tribe/Models/Event.php`: 
`isVirtual`
`virtualUrl`
`virtualEmbedVideo`
`virtualLinkedButton`
`virtualLinkedButtonText`
`virtualShowEmbedAt`
`virtualShowEmbedTo`
`virtualShowLeadUp`
`virtualIsLinkable`
`virtualIsImmediate`
`virtualShouldShowEmbed`
`virtualShouldShowLink`

## What's not included.
- GQL equivalents of helper functions. I'm working under the assumption that if it isn't saved to the event meta, its beyond the scope of the plugin. Correct me if I'm wrong.
- Meta fields for Zoom (located at `src/Tribe/Meetings/Zoom/Event_Meta.php`). I don't have access to the Zoom API, so I can't reasonably test it. If you want me to add them in blind, I'm happy to.
- Unit tests. This is beyond my skill-set.

## Feedback please.
I chose to stick to the naming that TEC gave its meta fields, even though their naming system isn't self-documenting (e.g. `virtualEmbedVideo` and `virtualLinkedButton` are bool, but differ in purpose to `virtualShouldShowEmbed` and `virtualShouldShowLink`). 
Ideally, Id change/merge some of these fields to make them easier for the user. Something like `virtualDisplayType: ("embed" | "link")` and `virtualShouldShow`. Thoughts?

### CODE REVIEW

**Comment by craigwilcox** [comment]
Hi @justlevine, 

We'll take a look at this as soon as we can. Thanks for your help on it!

**Review by bordoni — COMMENTED** [review]
I like where this is at so far. Lets make sure we test the composer piece we talked. We should also explore the `slic` path afterwards, I dont want us to invest too much on maintaining two test "frameworks" if we can avoid it..

**Comment by kidunot89** [comment]
Agree, that's why I made this a separate workflow. It was meant to be temporary.

**Comment by kidunot89** [comment]
Closed because CI secret are unreadable from PR across forks.

**Pull request closed without merging**
